### ISSUE TITLE
Figure out reporting

### ISSUE THREAD

**Issue by rynowak** [aspnet/Stress#5]
Can we use the xUnit message listener?

**Comment by NTaylorMullen** [comment]
Well, investigated a bit and due to how the official DNX runner (`xunit.runner.dnx`) is built there's the following limitation:

To allow the interception/control of custom reporting based on command line parameters we'd need to force users to always provide an output mechanism (would not be able to have a default). 

Example: `dnx test -console` 

_Note:_ We would not be able to do something like `dnx test -reportStressOutput console`, the provided command line extensibility only allows valueless parameters.

Also, if a `-console` or `-file` format was not provided the reporting would use the normal (non-stress test enabled) reporting infrastructure.

Potential alternatives/fixes:
1. Force test running to _only_ be configurable via configuration files.
2. Provide our own stress test runner to allow us to propagate command line arguments into the extensible reporting pieces.

/cc @rynowak @anurse @pranavkm

**Comment by NTaylorMullen** [comment]
Context for @bradwilson. We're building a stress testing framework on top of xUnit that will have custom messages flowing through the system. In addition to the new messages, we need to control how/where they're output/collected.

I investigated using the `IRunnerReporter` extensibility to hijack the `IMessageSink` and `IReportLogger` which is where I encountered the above limitation.

**Comment by analogrelay** [comment]
I don't have a major problem with making a relatively small fork of the official DNX runner to enable stress scenarios. We should definitely try to contribute any changes we end up making upstream, but until then this is a fairly specific scenario we're working on.

**Comment by pranavkm** [comment]
If the only limitation is that we'd have to specify a logger as an argument (which would be embedded in the `test` command), perhaps we can live with it specifying it. I'd prefer we call out that it's a stress related reporter - `-stressreport` or something along those lines?

**Comment by bradwilson** [comment]
I'm confused. Who is this tool for? Just you, or the general public?
- If it's just you, write a reporter, and set it up by default in your `test` command.
- If it's for the general public, then it sounds like you're building a new runner. Fork the source and ship it as a new thing.

**Comment by NTaylorMullen** [comment]
Decided for now to require specific opt-in via command line options for reporting. This is in.
